languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Lily's website"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "27 December 2023"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
name = "Lily Koffman"
image = "img/headshot_new.jpeg"
headline = "I'm only human"
bio = "A little bit about you"
 links = [
  { email = "mailto:lkoffma2@jh.edu" },
  { github = "https://github.com/lilykoff/"},
  { linkedin = "https://www.linkedin.com/in/lily-koffman-720b13152/"},
  { medium = "https://medium.com/@lilykoffman"},
  { gscholar = "https://scholar.google.com/citations?user=lOh2k5YAAAAJ&hl=en"},
  { orchid = "https://orcid.org/0000-0003-1543-2896"},
  { rgate = "https://www.researchgate.net/profile/Lily-Koffman}
 ]

